version: '2'
services:
  propertyupdate-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/propertyUpdate/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=propertyUpdate
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
